### ISSUE TITLE
convert docx files to txt format

### ISSUE THREAD

**Issue by LinguList** [hanproj/stelae#1]
The format used in the docx files is actually perfect for our purpose.

To render the data in our txt format, minimal requirements are only needed. 

@ashhenson, here is what I would suggest you to do (if you are in charge here).

You just copy-paste the file from word to a txt file, you could maybe use individual txt files per poem, but also do all in one file.

Then, adjusting is easy, using our `@` construct.

So 

```
十五：《秥蟬縣平山神祠碑》，東漢建武元年至十年（23-34），P32

惟平山君，德配代嵩
承天【出】□，□佑秥蟬
興甘風雨，惠閏土田
□□壽考，五穀豐【成】
盜賊不起，□（主凡）□臧
出入吉利，咸受神光
```

becomes

```
@poem: 十五
@title: 秥蟬縣平山神祠碑
@chinese_date: 東漢建武元年至十年
@date: 23-34
@page: 32

惟平山君，德配代嵩
承天【出】□，□佑秥蟬
興甘風雨，惠閏土田
□□壽考，五穀豐【成】
盜賊不起，□（主凡）□臧
出入吉利，咸受神光
```

**Comment by LinguList** [comment]
Once this is available as a text-file, we can prepare it for being annotated manually in rhyant, or automatically processed by some tools in CLDF.

**Comment by nh36** [comment]
Be careful, the docx contains some images for rare/strange characters, so I think maybe it should be first saved as .html and not direclty to .txt. (To annotate I personally think we should use Julien's method, especially since, combined with the csv files for the received corpus the data size is probably large enough.)

**Comment by LinguList** [comment]
We can annotated automatically first, then we should make sure Julien's 
method is available from within Python scripts in the workflows, but 
that is hopefully easy to accomplish.

**Comment by nh36** [comment]
@ashhenson The files are now in .txt, so this can be resolved, no? Maybe it is not yet CLDF or not yet annotated, but in either case, the issue needs to be changed, renamed if not resolved.

**Comment by ashhenson** [comment]
The files are in TXT format, so I'm closing this out, but will open another issue regarding getting them into CLDF format.

**Comment by ashhenson** [comment]
The files are in TXT format, so I'm closing this out, but will open another issue regarding getting them into CLDF format.
